### ISSUE TITLE
[Question] Build script instructions

### ISSUE THREAD

**Issue by AYastrebov** [stasel/WebRTC#19]
Hello! First of all thank you for maintaining this repo.
I have a question about build script. I've tried to build it my own, but unfortunately with no luck.

`IOS_64_BIT=true BUILD_VP9=true BITCODE=true sh build.sh`

Can you provide some instructions on how to use the script to correctly build iOS framework with bitcode enabled?

Thanks!

**Comment by stasel** [comment]
Hi @AYastrebov 
The commands looks good. I suggest running it from the main folder: `sh scripts/build.sh` just in case.
Can you share the error message you see?

**Comment by stasel** [comment]
After some investigation I do see an issue with building the library on later branches. I'm currently trying to fix it.
Meanwhile as a workaround you can use `BRANCH=branch-heads/4577` to build WebRTC M93 which is the latest stable version.

**Comment by AYastrebov** [comment]
Here is the error I get. Seems like conflicting parameters

`
ERROR at //BUILD.gn:125:5: Replacing nonempty list.
    defines = [ "WEBRTC_ENABLE_OBJC_SYMBOL_EXPORT" ]
    ^------
This overwrites a previously-defined nonempty list with another nonempty list.
See //BUILD.gn:122:15: for previous definition
    defines = [ "WEBRTC_ENABLE_SYMBOL_EXPORT" ]
              ^-------------------------------
Did you mean to append/modify instead? If you really want to overwrite, do:
  foo = []
before reassigning.
`

**Comment by stasel** [comment]
I managed to apply a small patch to fix the build error
