### ISSUE TITLE
[macos] RTCAudioSession.h not found

### ISSUE THREAD

**Issue by zibozeng** [stasel/WebRTC#20]
I tried use swift package manager to include the framework, and it turned out that this class (the one in the title) is not in the scope.  

and then i tried to drag the precompiled framework that you built in another repository, and remains the same. 

Then i went to check the folder of header files, in which i couldn't find "rtcaudiosession.h". Is this a mistake or it is what it supposed to be like? 

IOS works fine.

**Comment by stasel** [comment]
Hi @zibozeng 
According to WebRTC build file, RTCAudioSession only included in iOS builds. Checking Google really quickly revealed that on macOS there is no need to use AVAudioSession (or RTCAudioSession)

**Comment by zibozeng** [comment]
> Hi @zibozeng
> According to WebRTC build file, RTCAudioSession only included in iOS builds. Checking Google really quickly revealed that on macOS there is no need to use AVAudioSession (or RTCAudioSession)

true, sorry for bothering, I figured it out last night, and this class is just a wrapper of avaudiosession to control the speaker. thanks for replying.
