### ISSUE TITLE
Why M94 is the last build with 32-bit binaries ?

### ISSUE THREAD

**Issue by jsellam** [stasel/WebRTC#25]
Hi,
Thank you very much for this job. But can you explain to me why the M94 is the last version to support 32-bit ?

Thx,
Jeremie.

**Comment by stasel** [comment]
Hi @jsellam ,
I decided to drop the 32-bit versions because the latest iOS version to support 32 bit devices is iOS 10 which is unlikely to be targeted today by most developers. In addition, something was broken while compiling 32 bit library so I decided it's a good time to drop it.
