### ISSUE TITLE
Delivering audio data on iOS's Broadcast Upload Extension

### ISSUE THREAD

**Issue by DevMile** [stasel/WebRTC#30]
WebRTC framework which support audio buffer from Broadcast Upload Extension

The problem and solution

A broadcast extension allows to broadcast your screen from iOS. However, an extension is an environment restricted compared to normal applications, and lacks the Audio Unit framework, which is required by the audio device module for iOS of WebRTC.

A broadcast extension can still receive sounds of applications and one recorded with microphone via RPBroadcastSampleHandler object. This fork fixes the audio device module on environments without the Audio Unit framework and adds interfaces to deliver data received via RPBroadcastSampleHandler: https://github.com/pixiv/webrtc/releases/tag/87.0.4280.142-pixiv0

Is there a way that @stasel WebRTC package include this feature from the fork https://github.com/pixiv/webrtc/releases/tag/87.0.4280.142-pixiv0?

**Comment by stasel** [comment]
Hi,
Unfortunately I don't have plans delivering modified version of WebRTC. Mostly because I am not a VoIP expert and have limited amount of time.

However, you can fork WebRTC repo, modify the code and compile it yourself. I have a link with instructions on how to compile the library yourself
