### ISSUE TITLE
Support for Newer Versions

### ISSUE THREAD

**Issue by gurhub** [stasel/WebRTC#34]
Hi thank you for your effort, 

currently, the [chromium dashboard](https://chromiumdash.appspot.com/branches) milestone hit version M101. Any plan for adding support for those?

Also, is there any plan for adding automation for newer versions? 

best

**Comment by stasel** [comment]
Hi @gurhub 
Yes I plan to update the scripts to support the latest WebRTC versions. Google changed some scripts recently. They require xcode 13.0 and not newer so I need to try to make it work.

Sorry for the inconvenience

**Comment by stasel** [comment]
Hi again, Updated the library to support latest WebRTC version M102

**Comment by gurhub** [comment]
Hey man, great news! Thank you for your efforts! 👏🏻😊👍🏻
