### ISSUE TITLE
Bitcode will be deprecated with Xcode 14

### ISSUE THREAD

**Issue by respan** [stasel/WebRTC#37]
Hello,

First of all, thank you for this distribution and work you've done.

According to Xcode 14 Beta [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes), Bitcode soon will be deprecated and App Store will no longer accept such submissions:

<img width="938" alt="Снимок экрана 2022-06-08 в 12 19 01" src="https://user-images.githubusercontent.com/420242/172517163-0514d112-3324-4ed5-b4a0-3afaa785d81a.png">
 
So, I believe that there isn't any need in Bitcode support in the near future

**Comment by stasel** [comment]
That is good news! I will remove bitcode support in the next release M103

**Comment by stasel** [comment]
Version M103 has been released without bitcode 🎉
