### ISSUE TITLE
Cannot run test in Xcode with SPM setup

### ISSUE THREAD

**Issue by bofeizhu** [stasel/WebRTC#56]
```
Library not loaded: @rpath/WebRTC.framework/WebRTC
  Referenced from: <E867BA81-A8CB-3F44-8389-6186947C4F5A> /***/Library/Developer/Xcode/DerivedData/RTCTest-egwdzqwcibwomgdqnalvxbmtovoh/Build/Products/Debug-iphonesimulator/RTCTestTests.xctest/RTCTestTests
  Reason: tried: '/***/Library/Developer/Xcode/DerivedData/RTCTest-egwdzqwcibwomgdqnalvxbmtovoh/Build/Products/Debug-iphonesimulator/WebRTC.framework/WebRTC' (code signature in <4C4C441D-5555-3144-A11C-D7D3A9440C26> '/***/Library/Developer/Xcode/DerivedData/RTCTest-egwdzqwcibwomgdqnalvxbmtovoh/Build/Products/Debug-iphonesimulator/WebRTC.framework/WebRTC' not valid for use in process: Trying to load an unsigned library)
```

Here is the sample project
https://github.com/bofeizhu/RTCTest

M1 Chip, Xcode 14.1, Run test with iPhone simulator

**Comment by bofeizhu** [comment]
The iphone-simulator binary might have the same code signing issue as the Catalyst binary in https://github.com/stasel/WebRTC/issues/44. Or it has something to do with missing arm64-simulator-test binary?

**Comment by bofeizhu** [comment]
Interestingly, if I roll back the version to M96, the test would run successfully.

**Comment by fixique** [comment]
Faced the same problem. Xcode 13.4.1, M1, via Cocoapods M106. When I build a test target on the simulator have the same crash. 

When build on intel mac everything works fine.

**Comment by bukira** [comment]
I have the same issue

**Comment by bukira** [comment]
any update, this is serious issue on M1 Macs

**Comment by bukira** [comment]
Still the same for 108

**Comment by CyonAlexRDX** [comment]
@bukira @fixique fixed in #61

**Comment by stasel** [comment]
Thanks everyone for reporting and thanks to @GhenadieVP for the fix.
I have release a minor patch 109.0.1 with the fix. Can anyone please confirm that the latest release fixes the issue?

Thanks!

**Comment by bofeizhu** [comment]
I can confirm this issue is fixed. Thank you @stasel !
