### ISSUE TITLE
Error running on Apple M1 Simulator in a Unit Test bundle: Trying to load an unsigned library

### ISSUE THREAD

**Issue by damontikr** [stasel/WebRTC#59]
Hi,

I'm trying to link with WebRTC when building a Unit Test Bundle.  The build process succeeds but when the Unit Test Bundle launches, it immediately fails with this error on my M1 Mac.

NOTE: Non-M1 Macs do not have this issue so I'm hoping there is a build configuration/setting that fixes this.

```
  Assertions: System: Failed to load the test bundle. 
  (0x0109): Library not loaded: @rpath/WebRTC.framework/WebRTC
  Reason: tried: '/.../Debug-iphonesimulator/WebRTC.framework/WebRTC' 
  (code signature in <> '/.../Debug-iphonesimulator/WebRTC.framework/WebRTC' not valid for use in process: Trying to load an unsigned library), 
  '/.../Debug-iphonesimulator/PackageFrameworks/WebRTC.framework/WebRTC' (errno=2), 
  ...
```

**Comment by bofeizhu** [comment]
Could be related to this issue https://github.com/stasel/WebRTC/issues/56

**Comment by CyonAlexRDX** [comment]
@damontikr @bofeizhu fixed in PR #61

**Comment by stasel** [comment]
Thanks everyone for reporting and thanks to @GhenadieVP for the fix.
I have release a minor patch 109.0.1 with the fix. Can anyone please confirm that the latest release fixes the issue?

Thanks!

**Comment by CyonAlexRDX** [comment]
@stasel confirmed works!
