### ISSUE TITLE
webrtc binary is being redownloaded each time project.pbxproj touched

### ISSUE THREAD

**Issue by ruslandoga** [stasel/WebRTC#6]
👋

I think this might be SPM issue but still, I wonder if you know of a way to stop SPM downloading webrtc binaries each time `project.pbxproj` changes (or it seems even when it just changes last modified date) which happens each time I merge/rebase branches? Maybe there is some kind of check that could be done on SPM level without downloading the binaries?

I've tried pinning the package to commit ref but it's still being redownloaded after pulling updates for a branch that include `project.pbxproj` changes.

I've also [asked that question on the forum](https://forums.swift.org/t/how-to-stop-spm-from-downloading-package-artefacts-every-time-project-changes/47327).

**Comment by stasel** [comment]
Hey, yeah this sounds like xcode/SPM issue so better reporting it there or in Apple dev forums.

Closing the issue for now
