### ISSUE TITLE
C++ interop in Swift

### ISSUE THREAD

**Issue by DePasqualeOrg** [stasel/WebRTC#79]
Would Swift's C++ interop make it possible to use the WebRTC source code directly in an Xcode project instead of a compiled binary? If this works, I imagine it would result in better type intelligence in Xcode.

**Comment by paxsonsa** [comment]
I believe that is theoretically possible but isn't c++ interop still experimental?

**Comment by DePasqualeOrg** [comment]
Ah, yes. It was released in Swift 5.9, but it looks like the API could still change: [https://forums.swift.org/t/c-interoperability-in-swift-5-9](https://forums.swift.org/t/c-interoperability-in-swift-5-9)
