### ISSUE TITLE
Pods

### ISSUE THREAD

**Issue by decanus** [stasel/WebRTC#8]
What is required to get this running with cocoapods? I would love to get it into my app but sadly need it as a pod.

**Comment by stasel** [comment]
Unfortunately I get an error when trying to publish the pod ([Related issue](https://github.com/CocoaPods/CocoaPods/issues/10204)].

I suggest to either link the framework manually for now or as a workaround you can clone the repo and in your Podfile specify a local path to the podspec. 
Alternatively you can add the repo as a git submodule as well.

Not the best solution and I hope that the next version of Cocoapods will fix the error I have

**Comment by decanus** [comment]
@stasel idk if local linking will work, when I try to link it by using a manual git path it comes up as empty.

**Comment by stasel** [comment]
I think linking it directly to your project(s) without cocoapods using xcode should work as well if thats an option. 

There is a podspec in the library which I think works locally. 

Let me know if you kind a good way to use the podspec without publishing the pod

**Comment by decanus** [comment]
Will have a look, the issue is linking the framework is a bit of a hasstle right now because it is even too big to upload to github.

**Comment by decanus** [comment]
Ok @stasel can confirm the pod does not work locally, when trying to import WebRTC it is not found. It also looks like the pod is empty.

**Comment by stasel** [comment]
Thanks for checking this out,
Is using Carthage an acceptable workaround for you? I just added instructions in the README file how to add the library using Carthage

**Comment by decanus** [comment]
I wonder if the issue could be that the zip file and framework name do not match?

**Comment by stasel** [comment]
I tried to change the zip file name but I got the same issue with `pod spec lint`. I think it's a cocoapods issue with xcframework files

**Comment by stasel** [comment]
Opened a ticket in Cocoapods. Lets hope it will get fixed soon
https://github.com/CocoaPods/CocoaPods/issues/10638

**Comment by stasel** [comment]
Update: After discussing the problem with cocoapods contributor, I managed to solve the problem. Cocoapods will be supported in the next release: M93 🎉

**Comment by stasel** [comment]
Cocoapods is now supported. 
You can add the following line to your Podfile:

```pod 'WebRTC-lib'```

and run `pod install`
