### ISSUE TITLE
Network problems with iOS 17

### ISSUE THREAD

**Issue by DePasqualeOrg** [stasel/WebRTC#80]
Since I updated my devices to iOS 17, I've had problems viewing video over WiFi via a STUN server. The video connection works well over a cell connection and TURN server, but the connection often drops after a few seconds over WiFi and STUN. I'm having trouble isolating the problem, and I can't reproduce it with the example app, but I'd be interested to hear if anyone else is experiencing this issue, since I've seen a few similar reports about networking issues related to WebRTC video and iOS 17.

**Comment by DePasqualeOrg** [comment]
The issues I was encountering now seem to be resolved, so I'll close this issue.

**Comment by stasel** [comment]
Hi, @DePasqualeOrg 
I'm happy that the issue has been resolved and thanks for closing the issue. Let me know if you still having issues with networking

**Comment by nmendiratta89** [comment]
@DePasqualeOrg what was the issue that you were facing and what was the resolution? We are also facing some issues using the library in iOS 17.

**Comment by DePasqualeOrg** [comment]
The connection would often drop after a second or two. The issue seems to be resolved for me now.

**Comment by Bhoon-coding** [comment]
@DePasqualeOrg  
How did you resolve this problem? I'm also facing with this issue.
The volume progressbar is up and down repeatly when I check volume progressbar only iOS 17 upper version.

**Comment by DePasqualeOrg** [comment]
@Bhoon-coding, it sounds like the problem you're describing might not be related to this issue.

**Comment by Bhoon-coding** [comment]
@DePasqualeOrg 
You're right. 
Is was not related to this issue. 
I'm sorry for the confusion.
